# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStackedWidget, QTabWidget, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1026, 533)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(220, 0, 831, 531))
        self.stackedWidget.setLineWidth(3)
        self.stackedWidget.setMidLineWidth(3)
        self.home = QWidget()
        self.home.setObjectName(u"home")
        self.label_3 = QLabel(self.home)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 10, 311, 31))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_3.setFont(font)
        self.stackedWidget.addWidget(self.home)
        self.receive_page = QWidget()
        self.receive_page.setObjectName(u"receive_page")
        self.tabWidget = QTabWidget(self.receive_page)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 10, 791, 521))
        self.address_settings = QWidget()
        self.address_settings.setObjectName(u"address_settings")
        self.generate_new_addr = QPushButton(self.address_settings)
        self.generate_new_addr.setObjectName(u"generate_new_addr")
        self.generate_new_addr.setGeometry(QRect(270, 350, 231, 51))
        self.address_qr = QLabel(self.address_settings)
        self.address_qr.setObjectName(u"address_qr")
        self.address_qr.setGeometry(QRect(300, 40, 200, 200))
        self.address_qr.setMinimumSize(QSize(200, 200))
        self.address_qr.setMaximumSize(QSize(200, 200))
        self.address_qr.setSizeIncrement(QSize(0, 0))
        self.address_qr.setBaseSize(QSize(0, 0))
        self.address_label = QPushButton(self.address_settings)
        self.address_label.setObjectName(u"address_label")
        self.address_label.setGeometry(QRect(230, 280, 331, 26))
        self.address_label.setFlat(True)
        self.tabWidget.addTab(self.address_settings, "")
        self.address_viewer = QWidget()
        self.address_viewer.setObjectName(u"address_viewer")
        self.addresses_table = QTableWidget(self.address_viewer)
        self.addresses_table.setObjectName(u"addresses_table")
        self.addresses_table.setGeometry(QRect(10, 50, 771, 431))
        self.pushButton_2 = QPushButton(self.address_viewer)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(10, 20, 141, 26))
        self.tabWidget.addTab(self.address_viewer, "")
        self.stackedWidget.addWidget(self.receive_page)
        self.send = QWidget()
        self.send.setObjectName(u"send")
        self.addr = QLineEdit(self.send)
        self.addr.setObjectName(u"addr")
        self.addr.setGeometry(QRect(80, 20, 311, 26))
        self.summ = QLineEdit(self.send)
        self.summ.setObjectName(u"summ")
        self.summ.setGeometry(QRect(80, 70, 311, 26))
        self.pushButton = QPushButton(self.send)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(80, 210, 191, 71))
        self.pushButton.setCheckable(False)
        self.hash = QLabel(self.send)
        self.hash.setObjectName(u"hash")
        self.hash.setGeometry(QRect(20, 170, 761, 20))
        self.hash.setOpenExternalLinks(True)
        self.note = QLineEdit(self.send)
        self.note.setObjectName(u"note")
        self.note.setGeometry(QRect(80, 120, 311, 26))
        self.stackedWidget.addWidget(self.send)
        self.history_page = QWidget()
        self.history_page.setObjectName(u"history_page")
        self.history_table = QTableWidget(self.history_page)
        self.history_table.setObjectName(u"history_table")
        self.history_table.setEnabled(True)
        self.history_table.setGeometry(QRect(10, 80, 781, 441))
        self.history_table.setMidLineWidth(0)
        self.history_table.setSortingEnabled(False)
        self.history_table.setRowCount(0)
        self.debet = QLabel(self.history_page)
        self.debet.setObjectName(u"debet")
        self.debet.setGeometry(QRect(30, 20, 351, 18))
        self.credit = QLabel(self.history_page)
        self.credit.setObjectName(u"credit")
        self.credit.setGeometry(QRect(30, 50, 451, 18))
        self.filter_history = QComboBox(self.history_page)
        self.filter_history.setObjectName(u"filter_history")
        self.filter_history.setGeometry(QRect(590, 50, 201, 21))
        self.filter_history.setEditable(False)
        self.load_button = QPushButton(self.history_page)
        self.load_button.setObjectName(u"load_button")
        self.load_button.setGeometry(QRect(590, 10, 151, 31))
        self.stackedWidget.addWidget(self.history_page)
        self.lock = QWidget()
        self.lock.setObjectName(u"lock")
        self.stackedWidget.addWidget(self.lock)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(10, 250, 181, 41))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 20, 66, 18))
        self.balance = QLabel(self.centralwidget)
        self.balance.setObjectName(u"balance")
        self.balance.setGeometry(QRect(20, 60, 131, 18))
        self.show_bal = QPushButton(self.centralwidget)
        self.show_bal.setObjectName(u"show_bal")
        self.show_bal.setGeometry(QRect(10, 150, 181, 41))
        self.receive_button = QPushButton(self.centralwidget)
        self.receive_button.setObjectName(u"receive_button")
        self.receive_button.setGeometry(QRect(10, 300, 181, 41))
        self.history = QPushButton(self.centralwidget)
        self.history.setObjectName(u"history")
        self.history.setGeometry(QRect(10, 350, 181, 41))
        self.setting = QPushButton(self.centralwidget)
        self.setting.setObjectName(u"setting")
        self.setting.setGeometry(QRect(10, 450, 181, 41))
        self.contacts = QPushButton(self.centralwidget)
        self.contacts.setObjectName(u"contacts")
        self.contacts.setGeometry(QRect(10, 400, 181, 41))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 121, 18))
        self.label.setMouseTracking(False)
        self.unconf_balance = QLabel(self.centralwidget)
        self.unconf_balance.setObjectName(u"unconf_balance")
        self.unconf_balance.setGeometry(QRect(20, 120, 131, 18))
        self.go_to_home = QPushButton(self.centralwidget)
        self.go_to_home.setObjectName(u"go_to_home")
        self.go_to_home.setGeometry(QRect(10, 200, 181, 41))
        font1 = QFont()
        font1.setBold(True)
        self.go_to_home.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.filter_history.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Simple Bitcoin (Testnet) Wallet", None))
        self.generate_new_addr.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0433\u0435\u043d\u0435\u0440\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043d\u043e\u0432\u044b\u0439 \u0430\u0434\u0440\u0435\u0441", None))
        self.address_qr.setText("")
        self.address_label.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.address_settings), QCoreApplication.translate("MainWindow", u"Tab 1", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.address_viewer), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.addr.setText(QCoreApplication.translate("MainWindow", u"\u0430\u0434\u0440\u0435\u0441", None))
        self.summ.setText(QCoreApplication.translate("MainWindow", u"\u0441\u0443\u043c\u043c\u0430", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c", None))
        self.hash.setText("")
        self.note.setText(QCoreApplication.translate("MainWindow", u"\u043f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435 (\u0432\u0438\u0434\u043d\u043e \u0442\u043e\u043b\u044c\u043a\u043e \u0432\u0430\u043c)", None))
        self.debet.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0435\u0433\u043e \u043f\u043e\u0441\u0442\u0443\u043f\u0438\u043b\u043e (\u0434\u0435\u0431\u0435\u0442):", None))
        self.credit.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0441\u0435\u0433\u043e \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e (\u043a\u0440\u0435\u0434\u0438\u0442, \u0431\u0435\u0437 \u0443\u0447\u0451\u0442\u0430 \u043a\u043e\u043c\u0438\u0441\u0441\u0438\u0438):", None))
        self.filter_history.setCurrentText("")
        self.load_button.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0411\u0410\u041b\u0410\u041d\u0421", None))
        self.balance.setText("")
        self.show_bal.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u0431\u0430\u043b\u0430\u043d\u0441", None))
        self.receive_button.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043b\u0443\u0447\u0438\u0442\u044c", None))
        self.history.setText(QCoreApplication.translate("MainWindow", u"\u0418\u0441\u0442\u043e\u0440\u0438\u044f", None))
        self.setting.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438", None))
        self.contacts.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0435\u043f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u043e", None))
        self.unconf_balance.setText("")
        self.go_to_home.setText(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u043c\u043e\u0439", None))
    # retranslateUi

